# Build configuration for https://www.tea-ci.org

build:
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - autoreconf -i
    - ./configure --enable-warning-as-error --without-btrfs_subvol_support
    - make
    - make check

matrix:
  arch:
    - 64
    - 32

